### ISSUE TITLE
 snapp_prep error: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by ewelinaklichowska** [mmatschiner/snapp_prep#7]
Hello,

I try to run snapp_prep.rb script to prepare my .xml file, and I've met an error:

Traceback (most recent call last):
        3: from snapp_prep.rb:471:in `<main>'
        2: from snapp_prep.rb:471:in `each'
        1: from snapp_prep.rb:472:in `block in <main>'
snapp_prep.rb:472:in `strip': invalid byte sequence in UTF-8 (ArgumentError)

Would you be so kind and help me? is there any solution to this error?

Best regards,
Ewelina

**Comment by mmatschiner** [comment]
Hi Ewelina,

Can you please provide the full command with which you executed the script?

Cheers,
Michael

**Comment by ewelinaklichowska** [comment]
Sure, full command is 
ruby snapp_prep.rb -p zergrac.phy -t zergrac_species.txt -c zergrac_constraints.txt -l 2000000 -x zergrac_snapp.xml

I don't know if it matters but I have ruby version 2.5.1p57 installed

thank you for the quick reply

**Comment by mmatschiner** [comment]
I assume there are non-standard characters or other formatting issues with the Phylip file. If you don’t find the issue, I could have a look at the file next week.
