### ISSUE TITLE
Cannot find taxon in data

### ISSUE THREAD

**Issue by carolinapinapaez** [mmatschiner/snapp_prep#9]
Hi, 

I'm having problems running my snapp.xml file. I'm not sure if my file was generated correctly. I'm attaching the spec.txt, and the constraints.txt files. I can email you the snapp.xml file since it's pretty big.

Loading package BEAST.app v2.7.6 SNAPP v1.6.1 BEAST.base v2.7.6 snapper v1.1.4 BEASTLabs v2.0.2

### this is how I ran the ruby script
`ruby snapp_prep.rb -p myfile.phy -t spc.txt -c constraints.txt -m 3000 -l 100000`

### Run snapp
`beast -threads 16 snapp.xml`

The error that I'm getting when running snapp is this one:
[spc.txt](https://github.com/mmatschiner/snapp_prep/files/13867291/spc.txt)
[constraints.txt](https://github.com/mmatschiner/snapp_prep/files/13867292/constraints.txt)

java.lang.RuntimeException: Cannot find taxon Afum in data
        at beast.base.evolution.tree.MRCAPrior.initialise(Unknown Source)
        at beast.base.evolution.tree.MRCAPrior.calculateLogP(Unknown Source)
        at beast.base.inference.CompoundDistribution.calculateLogP(Unknown Source)
        at beast.base.inference.CompoundDistribution.calculateLogP(Unknown Source)
        at beast.base.inference.State.robustlyCalcPosterior(Unknown Source)
        at beast.base.inference.MCMC.run(Unknown Source)
        at beastfx.app.beast.BeastMCMC.run(Unknown Source)
        at beastfx.app.beast.BeastMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at beast.pkgmgmt.launcher.BeastLauncher.run(Unknown Source)
        at beast.pkgmgmt.launcher.BeastLauncher.main(Unknown Source)

Thank you :)!

**Comment by mmatschiner** [comment]
Hi, your `spc.txt` indicates that your dataset includes only a single species, "Afum". In that case, phylogenetic inference with SNAPP (or any other tool) wouldn't really make sense. Can you group individuals into populations? Then you could infer the phylogeny of those populations with SNAPP.

**Comment by carolinapinapaez** [comment]
Hi Michael, thanks for the prompt response. I modified my spc.txt file as suggested, and SNAPP is running with no complaints. Thanks again for your help.
